apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gagantest
  name: gagansvc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: gagantest
status:
  loadBalancer: {}